export { default as Footer } from './footer'
export { default as BlogContainer } from './Blog/blogContainer'
export { default as Login } from './LoginRegister/Login/login'
export { default as LoginModal } from './LoginRegister/Login/loginModal'
export { default as RegisterModal } from './Register/registerModal'
export { LogOrReg } from './LoginRegister/logOrReg'